#include "kernel.h"
/*
 TIPO: FUNCION

 DESCRIPCION: Mete el PCB recibido por parametro a la cola de new

 PARAMETROS: PCB

 CUANDO ACTUA: cuando se lo llama en la funcion atender_cliente()
*/
void ingreso_a_new(t_pcb* pcb);

/*
 TIPO: HILO

 DESCRIPCION: PASA UN PCB DE LA COLA DE NEW A LA COLA DE READY, ALGORITMO DE CORTO PLAZO FIFO

 PARAMETROS: NINGUNO

 CUANDO ACTUA: CUANDO HAY LUGAR EL GRADO DE MULTIPROGRAMACION LO PERMITE Y NO HAY PROCESOS EN SUSPENDIDO READY
*/
void* pasar_a_ready();

/*
 TIPO: HILO

 DESCRIPCION: PASA EL PROCESO (EN REALIDAD EL PCB) QUE SE ENCUENTRA EJECUTANDO A UNA LISTA DE EXIT (LO LIBERA, NO LO GUARDA)

 PARAMETROS: PCB

 CUANDO ACTUA: CUANDO SE RECIBE LA INSTRUCCION DEL CPU PARA TERMINAR EL PROCESO
*/
void executing_a_exit();

void crear_tabla_proceso(t_pcb* pcb);


